# Generated by Django 2.2.3 on 2019-11-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称')),
                ('capital', models.FloatField(verbose_name='总资产')),
                ('money_lock', models.FloatField(verbose_name='股票资产')),
                ('money_rest', models.FloatField(verbose_name='现金资产')),
                ('deal_action', models.CharField(max_length=100, verbose_name='交易动作')),
                ('ts_code', models.CharField(max_length=100, verbose_name='股票代码')),
                ('deal_price', models.FloatField(verbose_name='成交价')),
                ('stock_vol', models.IntegerField(verbose_name='成交量(股)')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='收益额')),
                ('profit_rate', models.FloatField(blank=True, null=True, verbose_name='收益率')),
                ('bz', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('state_dt', models.CharField(max_length=100, verbose_name='交易日期')),
                ('hold_days', models.IntegerField(blank=True, default=0, null=True, verbose_name='持有时间')),
                ('serial', models.IntegerField(verbose_name='序列号')),
            ],
        ),
        migrations.CreateModel(
            name='MyStockPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=100, verbose_name='股票代码')),
                ('buy_price', models.FloatField(verbose_name='买入价格')),
                ('hold_vol', models.IntegerField(verbose_name='持仓量（股）')),
                ('hold_days', models.IntegerField(verbose_name='持仓天数')),
            ],
        ),
    ]
