# Generated by Django 2.2.3 on 2019-11-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QTdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycapital',
            name='hold_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='持有时间'),
        ),
        migrations.AddField(
            model_name='mycapital',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='名称'),
        ),
    ]
