# Generated by Django 2.2.3 on 2019-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QTdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystockpool',
            name='opdate',
            field=models.CharField(default='', max_length=100, verbose_name='开仓时间'),
        ),
    ]
