# Generated by Django 2.2.3 on 2019-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecoder',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='表名')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('status', models.CharField(max_length=30, verbose_name='更新状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('period', models.CharField(max_length=100, verbose_name='更新周期')),
                ('rate', models.CharField(default='5s', max_length=30, verbose_name='更新速率')),
                ('task', models.CharField(max_length=30, verbose_name='任务')),
                ('params', models.CharField(blank=True, max_length=500, null=True, verbose_name='参数')),
                ('start_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='开始时间')),
                ('end_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '同步记录',
                'verbose_name_plural': '同步记录',
            },
        ),
    ]
