# Generated by Django 2.2.3 on 2019-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_db', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash',
            field=models.IntegerField(default=100000, verbose_name='现金'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stock',
            field=models.ManyToManyField(to='sync_db.SyncDataStockBasic', verbose_name='股票'),
        ),
    ]
