# Generated by Django 2.2.3 on 2019-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDataDailyBasic',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=100)),
                ('trade_date', models.CharField(max_length=100)),
                ('close', models.FloatField(blank=True, null=True)),
                ('turnover_rate', models.FloatField(blank=True, null=True)),
                ('turnover_rate_f', models.FloatField(blank=True, null=True)),
                ('volume_ratio', models.FloatField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('pe_ttm', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('ps', models.FloatField(blank=True, null=True)),
                ('ps_ttm', models.FloatField(blank=True, null=True)),
                ('total_share', models.FloatField(blank=True, null=True)),
                ('float_share', models.FloatField(blank=True, null=True)),
                ('free_share', models.FloatField(blank=True, null=True)),
                ('total_mv', models.FloatField(blank=True, null=True)),
                ('circ_mv', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_data_daily_basic',
            },
        ),
        migrations.CreateModel(
            name='SyncDataNews',
            fields=[
                ('datetime', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(default='000000', max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sync_data_news',
            },
        ),
        migrations.CreateModel(
            name='SyncDataShibor',
            fields=[
                ('date', models.CharField(default='00000000', max_length=100, primary_key=True, serialize=False)),
                ('on', models.FloatField(blank=True, null=True)),
                ('number_1w', models.FloatField(blank=True, db_column='1w', null=True)),
                ('number_2w', models.FloatField(blank=True, db_column='2w', null=True)),
                ('number_1m', models.FloatField(blank=True, db_column='1m', null=True)),
                ('number_3m', models.FloatField(blank=True, db_column='3m', null=True)),
                ('number_6m', models.FloatField(blank=True, db_column='6m', null=True)),
                ('number_9m', models.FloatField(blank=True, db_column='9m', null=True)),
                ('number_1y', models.FloatField(blank=True, db_column='1y', null=True)),
            ],
            options={
                'db_table': 'sync_data_shibor',
            },
        ),
        migrations.CreateModel(
            name='SyncDataStock5Minute',
            fields=[
                ('ts_code', models.TextField(blank=True, null=True)),
                ('trade_time', models.CharField(default='000000', max_length=100, primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('ma10', models.FloatField(blank=True, null=True)),
                ('ma_v_10', models.FloatField(blank=True, null=True)),
                ('ma20', models.FloatField(blank=True, null=True)),
                ('ma_v_20', models.FloatField(blank=True, null=True)),
                ('ma30', models.FloatField(blank=True, null=True)),
                ('ma_v_30', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_data_stock_5minute',
            },
        ),
        migrations.CreateModel(
            name='SyncDataStockBasic',
            fields=[
                ('ts_code', models.CharField(default='000000', max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('list_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_data_stock_basic',
            },
        ),
        migrations.CreateModel(
            name='SyncDataStockDay',
            fields=[
                ('trade_date', models.CharField(default='000000', max_length=100, primary_key=True, serialize=False)),
                ('ts_code', models.TextField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('pre_close', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('pct_chg', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('turnover_rate', models.FloatField(blank=True, null=True)),
                ('volume_ratio', models.FloatField(blank=True, null=True)),
                ('ma10', models.FloatField(blank=True, null=True)),
                ('ma_v_10', models.FloatField(blank=True, null=True)),
                ('ma20', models.FloatField(blank=True, null=True)),
                ('ma_v_20', models.FloatField(blank=True, null=True)),
                ('ma30', models.FloatField(blank=True, null=True)),
                ('ma_v_30', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_data_stock_day',
            },
        ),
    ]
